version = 0.1
[default.deploy.parameters]
stack_name = "pubsub-to-sqs"
resolve_s3 = true
s3_prefix = "pubsub-to-sqs"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
